apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: beerlog
  name: beerlog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beerlog
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: beerlog
    spec:
      containers:
      - image: beerlog:1.0
        name: beerlog
	ports:
	- containerPort: 8080
        resources: {}
status: {}
