name: CI
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.8', '3.10']
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: Install Poetry
        run: pip install --upgrade pip && pip install poetry

      - name: Install Project
        run: poetry install
      
      - name: Look for style errors
        run: poetry run flake8 beerlog
      
      - name: Look for auto format errors
        run: poetry run black -l 79 --check --diff beerlog tests
      
      - name: Run tests
        run: poetry run pytest -v --junitxml=test-result.xml
      
      - name: publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-result.xml
          check_name: Test Result (Python ${{matrix.python-version}})
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/day4'
    steps:
      - uses: actions/checkout@v2

      - name: Login no Docker Hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Buildando a imagem
        run: docker build -t lucascavalare85/beerlog:2.0 --file docker/Dockerfile .

      - name: Push para o Docker Hub
        uses: actions-hub/docker@master
        with:
          args: push docker.io/lucascavalare85/beerlog:2.0

      - name: Deploy da APP para o K8s
        uses: docker/build-push-action@master
        env: 
          RELEASE_IMAGE: lucascavalare85/beerlog:2.0
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          run: kubectl apply -f kubernetes/deployment.yaml --record

      - name: Deploy do service da APP
        uses: docker/build-push-action@master
        env: 
          RELEASE_IMAGE: lucascavalare85/beerlog:2.0
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          run: kubectl apply -f kubernetes/service.yaml --record
